name: Mean
kind: personalized

init:
  user_encoder_kwargs:
    aggregation_mode: mean
    embedding_dim: ${language_model.embedding_dim}
  language_model: ${language_model.name}
  learning_rate: ${training.learning_rate}
  margin: 0.1